version: "3.7"

services:
  app:
    container_name: blog-server
    build:
      args:
        user: dev
        uid: 1000
      context: .
      dockerfile: Dockerfile
    environment:
      - NODE_ENV=production
      - APP_PORT=3000
      - APP_SECRET=production
      - DB_HOST=db
      - DB_PORT=27017
      - DB_NAME=blog
    ports:
      - "3000:3000"
    depends_on:
        - db

  db:
    image: mongo:5.0.6
    container_name: blog-db
    environment:
      - PUID=1000
      - PGID=1000
    volumes:
      - database:/database

volumes:
  database: {}