version: "3.9"

services:
  app:
    image: ${TAG_COMMIT}
    container_name: blog-server
    build:
      args:
        user: dev
        uid: 1000
      context: .
      dockerfile: Dockerfile
    environment:
      - NODE_ENV=production
      - APP_PORT=3000
      - APP_SECRET=production
      - DB_HOST=db
      - DB_PORT=27017
      - DB_NAME=blog
    ports:
      - ${APP_PORT}:${APP_PORT}
    depends_on:
        - db
    volumes:
      - ./:/app

  db:
    image: mongo:5.0.6
    container_name: blog-db
    environment:
      - PUID=1000
      - PGID=1000
    volumes:
      - ./database:/database

